// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "../IdZodSchema";

export const CreateZodSchema = z.object({
  body: z.object({
    propertyId: IdZodSchema.optional(),
    fullname: z.string().nonempty(),
    phone: z.string().length(10).optional(),
    mobile: z.string().length(10),
    email: z.string().email(),
    addressLn1: z.string().nonempty(),
    addressLn2: z.string().nonempty(),
  }),
});

export const GetByIdZodSchema = z.object({
  params: z.object({
    landlordId: IdZodSchema,
  }),
});

export const UpdateZodSchema = z.object({
  body: z.object({
    propertyId: IdZodSchema.optional(),
    fullname: z.string().nonempty().optional(),
    phone: z.string().length(10).optional(),
    mobile: z.string().length(10).optional(),
    email: z.string().email().optional(),
    addressLn1: z.string().nonempty().optional(),
    addressLn2: z.string().nonempty().optional(),
  }),
  params: z.object({
    landlordId: IdZodSchema,
  }),
});
