// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "../IdZodSchema";

const Tenant = z.object({
  propertyId: IdZodSchema.optional(),
  fullname: z.string().nonempty(),
  phone: z.string().length(10).optional(),
  mobile: z.string().length(10),
  email: z.string().email(),
});

export const CreateZodSchema = z.object({
  body: Tenant,
});

export const GetByIdZodSchema = z.object({
  params: z.object({
    tenantId: IdZodSchema,
  }),
});

export const UpdateZodSchema = z.object({
  body: Tenant.deepPartial(),
  params: z.object({
    tenantId: IdZodSchema,
  }),
});
