// Generated by ts-to-zod
import { AnyZodObject, z } from "zod";
import IdZodSchema from "./id.zod";
import AddressZodSchema from "./address.zod";

class LandlordZod {
  static LandlordSchema: AnyZodObject = z.object({
    propertyId: IdZodSchema.optional(),
    fullname: z.string().nonempty(),
    phone: z.string().length(10).optional(),
    mobile: z.string().length(10),
    email: z.string().email(),
    address: AddressZodSchema,
  });

  static CreateSchema = z.object({
    body: this.LandlordSchema,
  });

  static GetByIdSchema = z.object({
    params: z.object({
      landlordId: IdZodSchema,
    }),
  });

  static UpdateSchema = z.object({
    body: this.LandlordSchema.deepPartial(),
    params: z.object({
      landlordId: IdZodSchema,
    }),
  });
}

export default LandlordZod;
