// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "./id.zod";
import AddressZodSchema from "./address.zod";
import PhoneZodSchema from "./phone.zod";

class LandlordZod {
  static LandlordSchema = z.object({
    propertyId: IdZodSchema.optional(),
    fullname: z.string().nonempty(),
    phone: PhoneZodSchema.optional(),
    mobile: PhoneZodSchema,
    email: z.string().email(),
    address: AddressZodSchema,
  });

  static CreateSchema = z.object({
    body: this.LandlordSchema,
  });

  static GetByIdSchema = z.object({
    params: z.object({
      landlordId: IdZodSchema,
    }),
  });

  static UpdateSchema = z.object({
    body: this.LandlordSchema.deepPartial(),
    params: z.object({
      landlordId: IdZodSchema,
    }),
  });
}

export default LandlordZod;
