// Generated by ts-to-zod
import { z } from "zod";

const LandlordZodSchema = z.object({
  propertyId: z.string().optional(),
  fullname: z.string(),
  phone: z.string().optional(),
  mobile: z.string(),
  email: z.string(),
  addressLn1: z.string(),
  addressLn2: z.string(),
});

export default LandlordZodSchema;
