// Generated by ts-to-zod
import { z } from "zod";

const PatchLandlordSchemaZodSchema = z.object({
  propertyId: z.string().optional(),
  fullname: z.string().optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  email: z.string().optional(),
  addressLn1: z.string().optional(),
  addressLn2: z.string().optional(),
});

export default PatchLandlordSchemaZodSchema;
