// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "./id.zod";
import AddressZodSchema from "./address.zod";

const Property = z.object({
  address: AddressZodSchema,
  landlordId: IdZodSchema,
  tenantId: IdZodSchema.optional(),
});

class PropertyZod {
  static CreateSchema = z.object({
    body: Property,
  });

  static GetByIdSchema = z.object({
    params: z.object({
      propertyId: IdZodSchema,
    }),
  });

  static UpdateSchema = z.object({
    body: Property.omit({ tenantId: true }).deepPartial(),
    params: z.object({
      propertyId: IdZodSchema,
    }),
  });
}

export default PropertyZod;
