// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "./id.zod";
import PhoneZodSchema from "./phone.zod";

class TenantZod {
  static TenantSchema = z.object({
    propertyId: IdZodSchema.optional(),
    fullname: z.string().nonempty(),
    phone: PhoneZodSchema.optional(),
    mobile: PhoneZodSchema,
    email: z.string().email(),
  });
  static CreateZodSchema = z.object({
    body: this.TenantSchema,
  });

  static GetByIdZodSchema = z.object({
    params: z.object({
      tenantId: IdZodSchema,
    }),
  });

  static UpdateZodSchema = z.object({
    body: this.TenantSchema.deepPartial(),
    params: z.object({
      tenantId: IdZodSchema,
    }),
  });
}

export default TenantZod;
