// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "./id.zod";

class TenantZod {
  static Tenant = z.object({
    propertyId: IdZodSchema.optional(),
    fullname: z.string().nonempty(),
    phone: z.string().length(10).optional(),
    mobile: z.string().length(10),
    email: z.string().email(),
  });
  static CreateZodSchema = z.object({
    body: this.Tenant,
  });

  static GetByIdZodSchema = z.object({
    params: z.object({
      tenantId: IdZodSchema,
    }),
  });

  static UpdateZodSchema = z.object({
    body: this.Tenant.deepPartial(),
    params: z.object({
      tenantId: IdZodSchema,
    }),
  });
}

export default TenantZod;
