// Generated by ts-to-zod
import { z } from "zod";

const tenantZodSchema = z.object({
  propertyId: z.string(),
  fullname: z.string(),
  phone: z.string().optional(),
  mobile: z.string(),
  email: z.string(),
});

export default tenantZodSchema;
