// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "../IdZodSchema";
import AddressZodSchema from "../AddressZodSchema";

export const CreateZodSchema = z.object({
  body: z.object({
    address: AddressZodSchema,
    landlordId: IdZodSchema,
    tenantId: IdZodSchema.optional(),
  }),
});

export const GetByIdZodSchema = z.object({
  params: z.object({
    propertyId: IdZodSchema,
  }),
});

export const UpdateZodSchema = z.object({
  body: z.object({
    address: AddressZodSchema.optional(),
    tenantId: IdZodSchema.optional(),
  }),
  params: z.object({
    propertyId: IdZodSchema,
  }),
});
