// Generated by ts-to-zod
import { z } from "zod";
import IdZodSchema from "../IdZodSchema";
import AddressZodSchema from "../AddressZodSchema";

const Property = z.object({
  address: AddressZodSchema,
  landlordId: IdZodSchema,
  tenantId: IdZodSchema.optional(),
});

export const CreateZodSchema = z.object({
  body: Property,
});

export const GetByIdZodSchema = z.object({
  params: z.object({
    propertyId: IdZodSchema,
  }),
});

export const UpdateZodSchema = z.object({
  body: Property.omit({ tenantId: true }).deepPartial(),
  params: z.object({
    propertyId: IdZodSchema,
  }),
});
